// Career Switch Calculator v1 — researched 15-role sheet.
// Research date: 2026-09-19. All pay bands are monthly cash after employee CPF,
// before tax, excluding AWS and bonuses ("base-like; bonus extra").
// See sources.md for the full evidence trail, gross figures, and open gaps.
// Every rubric score is a single-rater application of SPEC Section 8.
const ROLES15 = [
  {
    id: 'data-analyst',
    title: 'Data analyst',
    entry_pay: 4646,
    settled_pay: 6765,
    pay_source: 'MOM Report on Occupational Wages 2024, "Statistical officer / Data analyst": gross P25 S$5,807 / median S$8,365. Cash after 20% employee CPF. base-like; bonus extra.',
    wage_label: 'MOM occupational wages, June 2024',
    reskill_list_price: 21000,
    subsidy_class: 'sctp-70',
    reskill_nett_base: 6300,
    reskill_nett_40plus: 6300,
    reskill_months: 6,
    reskill_source: 'BCG Singapore SCTP: RISE 2.0 Applied AI and Data Analytics (MySkillsFuture TGS-2025052661), about 4 months full-time. Full fee S$21,000; S$6,300 after 70% SSG funding (subsidy-only; SkillsFuture Credit not subtracted). 40+ MCES rate not verified for this course, so the 40+ nett equals the base nett; flagged in sources.md. reskill_months 6 covers the course plus job search.',
    allowance: 0,
    hours_score: 50,
    hours_note: 'PMET 44-48h norm with crunch around reporting cycles and launches (SPEC 8.1: office norm anchor).',
    sovereignty_score: 65,
    sovereignty_note: 'Hybrid is the norm in most employers, but sprint deadlines and stakeholder windows set the schedule (SPEC 8.2).',
    meaning_score: 58,
    meaning_cite: 'Single-rater. Craft depth and autonomy 25/40 (analytical craft, moderate autonomy); purpose legibility 15/30 (insight legibility, commercial purpose); variety and feedback 18/30 (varied problems, stakeholder feedback). Human contact excluded from meaning per SPEC 8.3.',
    stability_score: 73,
    stability_cite: 'Single-rater. Demand growing 50 (MOM Job Vacancies, IMDA Digital Economy Report 2025); automation medium 18 (AI compresses routine reporting; problem-framing stays human); moat open entry 5 (SPEC 8.4).',
    demand: 'growing',
    demand_date: '2026-09',
    automation_exposure: 'medium',
    automation_date: '2026-09',
    contract_mix: 'Mostly direct employment by banks, tech firms, government agencies and consultancies; contract roles common in banks.',
    incomeStability: 'stable',
    gates: { minResidency: 'ep', licenceMonths: null, licence_note: 'No licence, registration or citizenship requirement. De-facto gate: portfolio of analysis projects.' },
    gates_review_date: '2026-09-19',
    tags: ['money', 'office', 'hybrid']
  },
  {
    id: 'software-developer',
    title: 'Software developer',
    entry_pay: 5326,
    settled_pay: 7287,
    pay_source: 'MOM Report on Occupational Wages 2024, "Software developer": gross P25 S$6,658 / median S$8,887. Cash after 20% employee CPF. base-like; bonus extra.',
    wage_label: 'MOM occupational wages, June 2024',
    reskill_list_price: 11650,
    subsidy_class: 'sctp-70-90',
    reskill_nett_base: 4977,
    reskill_nett_40plus: 1933,
    reskill_months: 7,
    reskill_source: 'BELLS SCTP Full Stack Developer (TGS-2023021703), 231.5 classroom hours (about 5 months). Full fee S$11,650; provider post-70% S$4,976.94; provider post-90% MCES S$1,932.94 (subsidy-only; SkillsFuture Credit not subtracted). reskill_months 7 covers the course plus job search and portfolio building.',
    allowance: 0,
    hours_score: 50,
    hours_note: 'PMET 44-48h norm with crunch around releases (SPEC 8.1: office norm anchor).',
    sovereignty_score: 100,
    sovereignty_note: 'Hybrid and outcome-based work is the norm; high choose-your-hours flexibility at most employers (SPEC 8.2).',
    meaning_score: 66,
    meaning_cite: 'Single-rater. Craft depth and autonomy 32/40 (deep technical craft, high build autonomy); purpose legibility 12/30 (product legibility, commercial purpose); variety and feedback 22/30 (varied builds, user and peer feedback). Human contact excluded from meaning per SPEC 8.3.',
    stability_score: 73,
    stability_cite: 'Single-rater. Demand growing 50 (MOM Job Vacancies 2025: among the most sought-after roles); automation medium 18 (AI coding assistants compress boilerplate; architecture stays human); moat open entry 5 (SPEC 8.4).',
    demand: 'growing',
    demand_date: '2026-09',
    automation_exposure: 'medium',
    automation_date: '2026-09',
    contract_mix: 'Mostly direct employment by tech firms, banks, startups and government tech agencies; contract roles common.',
    incomeStability: 'stable',
    gates: { minResidency: 'ep', licenceMonths: null, licence_note: 'No licence, registration or citizenship requirement. De-facto gate: portfolio and technical interviews.' },
    gates_review_date: '2026-09-19',
    tags: ['money', 'office', 'hybrid']
  },
  {
    id: 'cybersecurity-analyst',
    title: 'Cybersecurity analyst',
    entry_pay: 4300,
    settled_pay: 6160,
    pay_source: 'MOM Report on Occupational Wages 2024, "Security operations specialist": gross P25 S$5,375 / median S$7,700. Cash after 20% employee CPF. base-like; bonus extra.',
    wage_label: 'MOM occupational wages, June 2024',
    reskill_list_price: 17268,
    subsidy_class: 'sctp-70-90',
    reskill_nett_base: 5183,
    reskill_nett_40plus: 2013,
    reskill_months: 6,
    reskill_source: 'NTUC LearningHub SCTP cybersecurity programme, about 4-5 months. Full fee S$17,267.50; S$5,182.95 after 70% funding; S$2,012.95 after 90% MCES (subsidy-only; SkillsFuture Credit not subtracted). reskill_months 6 covers the course plus job search and certification prep.',
    allowance: 0,
    hours_score: 50,
    hours_note: 'SOC shifts 44-50h plus incident callouts; rostered coverage in MSSPs, banks and telcos (SPEC 8.1).',
    sovereignty_score: 0,
    sovereignty_note: 'Rigid 24/7 rotating shifts in most SOC roles; flexibility only at senior level (SPEC 8.2).',
    meaning_score: 68,
    meaning_cite: 'Single-rater. Craft depth and autonomy 28/40 (technical craft, incident-response autonomy); purpose legibility 20/30 (protection mission is legible); variety and feedback 20/30 (varied threats, incident feedback). Human contact excluded from meaning per SPEC 8.3.',
    stability_score: 85,
    stability_cite: 'Single-rater. Demand growing 50 (MOM 2026 Shortage Occupation List; IMDA Digital Economy Report 2025); automation low 30 (AI assists triage; adversarial adaptation stays human); moat open entry 5 (SPEC 8.4).',
    demand: 'growing',
    demand_date: '2026-09',
    automation_exposure: 'low',
    automation_date: '2026-09',
    contract_mix: 'Employed by MSSPs, banks, telcos, government agencies and large enterprises; shift rosters standard in SOC roles.',
    incomeStability: 'stable',
    gates: { minResidency: 'ep', licenceMonths: null, licence_note: 'No licence for commercial SOC roles. Some government and defence-adjacent postings require SC citizenship plus security clearance; narrow, not modelled.' },
    gates_review_date: '2026-09-19',
    tags: ['money', 'stability', 'shifts']
  },
  {
    id: 'ux-designer',
    title: 'UX designer',
    entry_pay: 4663,
    settled_pay: 6306,
    pay_source: 'Entry: MOM OW 2025 under-30 median for "Interaction designer", gross S$5,829, used as an explicit P25 proxy (P25 unpublished). Settled: MOM OW 2024 median gross S$7,883. Cash after 20% employee CPF. base-like; bonus extra.',
    wage_label: 'MOM occupational wages, June 2024 / June 2025',
    reskill_list_price: 20492,
    subsidy_class: 'sctp-70-90',
    reskill_nett_base: 6148,
    reskill_nett_40plus: 2388,
    reskill_months: 7,
    reskill_source: 'NTU SCTP Advanced Professional Certificate in AI-Powered UX Design and Digital Product Strategy, part-time 4 months. List S$20,492; provider S$6,147.60 after 70%; provider S$2,387.60 after 90% MCES (subsidy-only; SkillsFuture Credit not subtracted). reskill_months 7 covers the course plus portfolio and job search. De-facto gate: portfolio of 2-3 case studies.',
    allowance: 0,
    hours_score: 50,
    hours_note: 'PMET 44-48h norm; agency and launch crunches (SPEC 8.1: office norm anchor).',
    sovereignty_score: 100,
    sovereignty_note: 'Remote and hybrid norm with choose-your-hours cultures at many employers (SPEC 8.2).',
    meaning_score: 77,
    meaning_cite: 'Single-rater. Craft depth and autonomy 35/40 (deep design craft, high product autonomy); purpose legibility 18/30 (user-outcome legibility); variety and feedback 24/30 (varied products, user feedback). Human contact excluded from meaning per SPEC 8.3.',
    stability_score: 73,
    stability_cite: 'Single-rater. Demand growing 50 (MOM Job Vacancies 2025); automation medium 18 (generative UI tools compress production; research stays human); moat open entry 5 (SPEC 8.4).',
    demand: 'growing',
    demand_date: '2026-09',
    automation_exposure: 'medium',
    automation_date: '2026-09',
    contract_mix: 'Employed by tech firms, banks, design studios and government digital teams; freelance and contract common.',
    incomeStability: 'stable',
    gates: { minResidency: 'ep', licenceMonths: null, licence_note: 'No licence, registration or citizenship requirement. De-facto gate: portfolio of 2-3 case studies.' },
    gates_review_date: '2026-09-19',
    tags: ['time', 'meaning', 'hybrid']
  },
  {
    id: 'digital-marketer',
    title: 'Digital marketer',
    entry_pay: 2943,
    settled_pay: 4240,
    pay_source: 'MOM Report on Occupational Wages 2024, "Digital marketing professional": gross P25 S$3,679 / median S$5,300. Cash after 20% employee CPF. base-like; bonus extra.',
    wage_label: 'MOM occupational wages, June 2024',
    reskill_list_price: 15220,
    subsidy_class: 'sctp-70-90',
    reskill_nett_base: 4977,
    reskill_nett_40plus: 1933,
    reskill_months: 6,
    reskill_source: 'BELLS SCTP digital marketing programme. List S$15,220 before GST; provider post-70% S$4,976.94; provider post-90% MCES S$1,932.94 (subsidy-only; SkillsFuture Credit not subtracted). reskill_months 6 covers the course plus job search and portfolio.',
    allowance: 0,
    hours_score: 50,
    hours_note: 'PMET 44-50h norm with campaign-launch spikes; agency roles hotter (SPEC 8.1).',
    sovereignty_score: 65,
    sovereignty_note: 'Hybrid common, but campaign windows and always-on channels set evenings (SPEC 8.2).',
    meaning_score: 60,
    meaning_cite: 'Single-rater. Craft depth and autonomy 22/40 (growth craft, moderate autonomy); purpose legibility 14/30 (commercial purpose); variety and feedback 24/30 (varied campaigns, metrics feedback). Human contact excluded from meaning per SPEC 8.3.',
    stability_score: 40,
    stability_cite: 'Single-rater. Demand stable 30 (vacancies persist but entry is crowded); automation high 5 (copy, creative variants, media buying and reporting are the most AI-exposed of the desk roles); moat open entry 5 (SPEC 8.4).',
    demand: 'stable',
    demand_date: '2026-09',
    automation_exposure: 'high',
    automation_date: '2026-09',
    contract_mix: 'Employed by brands, agencies, e-commerce firms and SMEs; freelance and contract common.',
    incomeStability: 'stable',
    gates: { minResidency: 'ep', licenceMonths: null, licence_note: 'No licence, registration or citizenship requirement. De-facto gate: portfolio of campaign work.' },
    gates_review_date: '2026-09-19',
    tags: ['time', 'office', 'hybrid']
  },
  {
    id: 'accountant',
    title: 'Accountant',
    entry_pay: 3640,
    settled_pay: 5360,
    pay_source: 'MOM Job Vacancies 2025: "Accountant" gross S$4,550-6,700/month (basic salary range for a top-10 in-demand role). Cash after 20% employee CPF. base-like; bonus extra. Note: MOM Job Vacancies reports basic salary ranges, which aligns with the calculator base-like basis.',
    wage_label: 'MOM job vacancies, 2025',
    reskill_list_price: 2000,
    subsidy_class: 'none',
    reskill_nett_base: 2000,
    reskill_nett_40plus: 2000,
    reskill_months: 9,
    reskill_source: 'ACCA part-time papers as an employability bridge (2-4 papers across two exam sessions, not full qualification): about S$2,000 total using ACCA official 2026 pricing. No SSG funding verified for this route. reskill_months 9 covers two exam sessions plus job search. This is the thinnest reskill evidence in the sheet; flagged in sources.md.',
    allowance: 0,
    hours_score: 50,
    hours_note: 'Office 44h norm; month-end, year-end and audit busy-season spikes (SPEC 8.1).',
    sovereignty_score: 35,
    sovereignty_note: 'Fixed schedules with close spikes; limited WFH in many firms (SPEC 8.2).',
    meaning_score: 57,
    meaning_cite: 'Single-rater. Craft depth and autonomy 30/40 (technical craft, moderate autonomy); purpose legibility 12/30 (commercial purpose); variety and feedback 15/30 (cyclical work, close feedback). Human contact excluded from meaning per SPEC 8.3.',
    stability_score: 88,
    stability_cite: 'Single-rater. Demand growing 50 (ISCA/EY: 6,000-7,000 more accountants needed; graduate numbers down); automation medium 18 (RPA takes reconciliation; judgement stays human); moat degree-gated 20 (degree effectively required; SPEC 8.4).',
    demand: 'growing',
    demand_date: '2026-09',
    automation_exposure: 'medium',
    automation_date: '2026-09',
    contract_mix: 'Employed by accounting firms, corporates, SMEs and the public sector; mostly permanent.',
    incomeStability: 'stable',
    gates: { minResidency: 'ep', licenceMonths: 36, licence_note: 'No statutory licence for in-house and commercial roles. ACRA public-accountant registration binds audit partners only. De-facto gate: relevant degree expected at entry; 2-4 ACCA papers alone do not open the switch. Modelled as 36 months so F3 bites inside the v1 window.' },
    gates_review_date: '2026-09-19',
    tags: ['money', 'stability', 'office']
  },
  {
    id: 'hr-executive',
    title: 'HR executive',
    entry_pay: 2240,
    settled_pay: 3200,
    pay_source: 'Entry: MOM Q1 2026 top entry-level PMET opportunities: "HR officer" gross S$2,800-3,500/month (low end used). Settled: MOM OW 2024 "Personnel / Human resource officer" median gross S$4,000. Cash after 20% employee CPF. base-like; bonus extra.',
    wage_label: 'MOM entry-level PMET data, Q1 2026 / occupational wages, June 2024',
    reskill_list_price: 1417,
    subsidy_class: 'standard-70',
    reskill_nett_base: 425,
    reskill_nett_40plus: 425,
    reskill_months: 3,
    reskill_source: 'SHRI HR development roadmap to IHRP certification: S$1,417 incl GST; S$425 after 70% SSG funding (subsidy-only; SkillsFuture Credit not subtracted). Note: IHRP-CP requires 3 years of HR experience; a fresh switcher uses the IHRP-CA entry track, and the entry-level course price was not separately verified; flagged in sources.md. reskill_months 3 covers short courses plus job search.',
    allowance: 0,
    hours_score: 75,
    hours_note: 'Standard office 44h norm; no role-specific long-hours series published (SPEC 8.1).',
    sovereignty_score: 65,
    sovereignty_note: 'Fixed schedule; hybrid common in large firms (SPEC 8.2).',
    meaning_score: 50,
    meaning_cite: 'Single-rater. Craft depth and autonomy 18/40 (process craft, bounded autonomy); purpose legibility 16/30 (workforce outcomes are legible); variety and feedback 16/30 (varied cases, employee feedback). Human contact excluded from meaning per SPEC 8.3.',
    stability_score: 33,
    stability_cite: 'Single-rater. Demand shrinking 10 (HR postings down sharply in late 2025); automation medium 18 (screening and HRIS automated; employee relations stay human); moat open entry 5 (SPEC 8.4).',
    demand: 'shrinking',
    demand_date: '2026-09',
    automation_exposure: 'medium',
    automation_date: '2026-09',
    contract_mix: 'Employed by corporates, SMEs and the public sector; mostly permanent.',
    incomeStability: 'stable',
    gates: { minResidency: 'ep', licenceMonths: null, licence_note: 'No licence, registration or citizenship requirement. IHRP certification is voluntary.' },
    gates_review_date: '2026-09-19',
    tags: ['time', 'office']
  },
  {
    id: 'enrolled-nurse',
    title: 'Enrolled nurse',
    entry_pay: 1640,
    settled_pay: 2496,
    pay_source: 'MOH community-care salary guidelines (14 Feb 2024): enrolled nurse starting monthly base gross S$2,050; job-band midpoint gross S$3,120. Excludes bonuses and allowances. Cash after 20% employee CPF. base-like; bonus extra.',
    wage_label: 'MOH community-care salary guidelines, Feb 2024',
    reskill_list_price: 0,
    subsidy_class: 'ccp-en',
    reskill_nett_base: 0,
    reskill_nett_40plus: 0,
    reskill_months: 27,
    reskill_source: 'WSG/MOH Career Conversion Programme for Enrolled Nurses (CCP-EN): Higher Nitec in Nursing, 2-year full-time train-and-place; course fees fully sponsored; 2-year service bond with 2 sureties. reskill_months 27 covers the 2-year programme plus SNB enrolment processing.',
    allowance: 1610,
    hours_score: 50,
    hours_note: 'Rostered shifts including nights, weekends and public holidays (SPEC 8.1).',
    sovereignty_score: 0,
    sovereignty_note: 'Rigid rosters; hospital nursing is roster-based with limited choose-your-hours flexibility (SPEC 8.2).',
    meaning_score: 82,
    meaning_cite: 'Single-rater. Craft depth and autonomy 32/40 (clinical craft, protocol-bounded autonomy); purpose legibility 28/30 (care outcomes are directly legible); variety and feedback 22/30 (varied patients, outcome feedback). Human contact excluded from meaning per SPEC 8.3.',
    stability_score: 100,
    stability_cite: 'Single-rater. Demand growing 50 (structural ageing-population demand; nursing among the hardest-to-fill PMET roles); automation low 30 (bedside care stays human); moat licensed 20 (SNB enrolment mandatory; SPEC 8.4).',
    demand: 'growing',
    demand_date: '2026-09',
    automation_exposure: 'low',
    automation_date: '2026-09',
    contract_mix: 'Employed by public hospitals, community-care providers and nursing homes; mostly permanent with shift allowances.',
    incomeStability: 'stable',
    gates: { minResidency: 'pr', licenceMonths: 27, licence_note: 'CCP-EN requires SC or PR per the official healthcare CCP FAQ. SNB enrolment only on completion of a 2-year SNB-approved programme; no route clears it under about 27 months. CCP-EN carries a 2-year service bond with 2 sureties.' },
    gates_review_date: '2026-09-19',
    tags: ['meaning', 'stability', 'shifts', 'licensing']
  },
  {
    id: 'electrician',
    title: 'Electrician',
    entry_pay: 1716,
    settled_pay: 2400,
    pay_source: 'MOM Report on Occupational Wages 2024, "Electrician": gross P25 S$2,145 / median S$3,000. Cash after 20% employee CPF. base-like; bonus extra. The settled band models the pre-licence employed tier; the EMA-licensed premium tier sits above it.',
    wage_label: 'MOM occupational wages, June 2024',
    reskill_list_price: 1252,
    subsidy_class: 'ite-subsidized',
    reskill_nett_base: 1252,
    reskill_nett_40plus: 1252,
    reskill_months: 24,
    reskill_source: 'ITE Nitec in Electrical Technology (Power and Control), 2 years full-time. SC fee S$626 per academic year (AY2026 schedule), S$1,252 total; already subsidised, so both netts equal the list price. reskill_months 24: employable as an electrical worker or helper under a licensed electrician from about 24 months. Full EMA Licensed Electrician needs about 2 years study plus 2 years SG experience (about 48 months total), outside the v1 window; the sheet models supervised employment, not the licence.',
    allowance: 0,
    hours_score: 50,
    hours_note: '44-48h plus overtime and on-call; site and maintenance schedules (SPEC 8.1).',
    sovereignty_score: 35,
    sovereignty_note: 'Fixed site schedules; self-employed licensed electricians choose jobs but live on call-outs (SPEC 8.2).',
    meaning_score: 68,
    meaning_cite: 'Single-rater. Craft depth and autonomy 32/40 (trade craft, job-level autonomy); purpose legibility 16/30 (working power and safety moderately legible); variety and feedback 20/30 (varied sites, fix feedback). Human contact excluded from meaning per SPEC 8.3.',
    stability_score: 80,
    stability_cite: 'Single-rater. Demand stable 30 (built-environment maintenance steady); automation low 30 (physical installation and fault-finding); moat licensed 20 (EMA licensing gates the premium tier; SPEC 8.4).',
    demand: 'stable',
    demand_date: '2026-09',
    automation_exposure: 'low',
    automation_date: '2026-09',
    contract_mix: 'Employed by electrical contractors, building-maintenance firms and MCSTs; self-employed sole-proprietors common for residential and small-commercial jobs.',
    incomeStability: 'stable',
    gates: { minResidency: 'ep', licenceMonths: null, licence_note: 'No licence needed to work under a licensed electrician. Full EMA Licensed Electrician needs about 48 months total, outside the v1 window; settled pay is the pre-licence tier.' },
    gates_review_date: '2026-09-19',
    tags: ['stability', 'hands-on', 'trades']
  },
  {
    id: 'plumber',
    title: 'Plumber',
    entry_pay: 1920,
    settled_pay: 1920,
    pay_source: 'MOM Report on Occupational Wages 2024, "Plumber": median gross S$2,400 (P25/P75 unpublished). Both entry and settled set to the median cash S$1,920 as a single-point band; entry is not separately observed. Conservative: licensed plumbers command a premium (see sources.md). Cash after 20% employee CPF. base-like; bonus extra.',
    wage_label: 'MOM occupational wages, June 2024 (one published median)',
    reskill_list_price: 4496,
    subsidy_class: 'bca-50-70',
    reskill_nett_base: 2434,
    reskill_nett_40plus: 1609,
    reskill_months: 36,
    reskill_source: 'BCA Academy Builder Certificate in Plumbing and Pipefitting (TGS-2024049505), 396 hours (6 months daytime / 11 months evenings). Full fee S$4,496 incl GST; S$2,433.61 after 50% funding; S$1,608.66 after 70% (SC 40+) (subsidy-only; SkillsFuture Credit not subtracted). Then 2 years supervised post-qualification experience under a licensed plumber, 40-hour SPS mentorship, and the PUB written/oral assessment. reskill_months 36 and licenceMonths 36 reflect this full path to PUB Licensed Plumber.',
    allowance: 0,
    hours_score: 50,
    hours_note: 'Full-time, often 6-day weeks in construction and maintenance; emergency call-outs for service plumbers (SPEC 8.1).',
    sovereignty_score: 35,
    sovereignty_note: 'Fixed schedule when employed; self-employed licensed plumbers choose jobs but live on call-outs (SPEC 8.2).',
    meaning_score: 64,
    meaning_cite: 'Single-rater. Craft depth and autonomy 30/40 (trade craft, job-level autonomy); purpose legibility 16/30 (working water and sanitation moderately legible); variety and feedback 18/30 (varied call-outs, immediate fix feedback). Human contact excluded from meaning per SPEC 8.3.',
    stability_score: 80,
    stability_cite: 'Single-rater. Demand stable 30 (PUB licensing constrains supply; town-council and ageing-HDB maintenance durable); automation low 30 (pipework is physical, in-situ, safety-regulated); moat licensed 20 (PUB Licensed Plumber mandatory since Apr 2018 for water-service and sanitary work; SPEC 8.4).',
    demand: 'stable',
    demand_date: '2026-09',
    automation_exposure: 'low',
    automation_date: '2026-09',
    contract_mix: 'Employed by mechanical and plumbing contractors, MCSTs and town councils; self-employed licensed plumbers on residential call-outs.',
    incomeStability: 'stable',
    gates: { minResidency: 'ep', licenceMonths: 36, licence_note: 'PUB Licensed Plumber: BCA Builder Certificate (or equivalent) plus 2 years post-qualification supervised experience, 40-hour SPS mentorship, written/oral assessment. Clears at about 36 months.' },
    gates_review_date: '2026-09-19',
    tags: ['stability', 'hands-on', 'trades', 'licensing']
  },
  {
    id: 'chef',
    title: 'Chef',
    entry_pay: 1856,
    settled_pay: 2016,
    pay_source: 'Food Services Progressive Wage Model (statutory ladder from 1 Jul 2026): Kitchen Assistant gross S$2,320; Cook (Quick-Service) gross S$2,470; Cook (Full-Service) gross S$2,520. Entry uses the Kitchen Assistant floor (a switcher enters at the bottom of the ladder); settled uses the Cook (Full-Service) rate. Cash after 20% employee CPF. base-like; bonus extra. Note: Senior Cook is left to market forces under PWM.',
    wage_label: 'Food Services PWM ladder, from July 2026',
    card_note: 'Resident cook pay is the PWM rung; the job competes with a WP/S-Pass kitchen.',
    reskill_list_price: 19893,
    subsidy_class: 'wsq-70-90',
    reskill_nett_base: 5968,
    reskill_nett_40plus: 2318,
    reskill_months: 18,
    reskill_source: 'SHATEC WSQ Diploma in Culinary Arts (modular WSQ levels; typically 12-18 months including industrial attachment). List price S$19,893 derived from the provider post-70% fee S$5,968.01; provider SC-40+ fee S$2,317.85 (MCES 90%) (subsidy-only; SkillsFuture Credit not subtracted). reskill_months 18 covers the diploma plus attachment. WSQ Food Safety Course Level 1 (1 day, about S$150) is mandatory for food handlers but not a real gate.',
    allowance: 0,
    hours_score: 0,
    hours_note: 'Split shifts (lunch plus dinner service), 10-12h days, 6-day weeks; weekends and public holidays are workdays (SPEC 8.1: lowest anchor).',
    sovereignty_score: 0,
    sovereignty_note: 'Rigid shifts; weekends and public holidays are peak work; very low choose-your-hours flexibility (SPEC 8.2).',
    meaning_score: 74,
    meaning_cite: 'Single-rater. Craft depth and autonomy 38/40 (deep culinary craft, high line autonomy); purpose legibility 14/30 (service outcome is legible; purpose is commercial); variety and feedback 22/30 (varied service, immediate plate feedback). Human contact excluded from meaning per SPEC 8.3.',
    stability_score: 73,
    stability_cite: 'Single-rater. Demand growing 50 (SkillsFuture Jobs-Skills Insights Jun 2026: robust expansion 2023-2025; persistent shortage); automation medium 18 (central kitchens and system-centric production; skilled line cooking stays manual); moat open entry 5 (SPEC 8.4).',
    demand: 'growing',
    demand_date: '2026-06',
    automation_exposure: 'medium',
    automation_date: '2026-09',
    contract_mix: 'Mostly employed by F&B operators (restaurants, caterers, central kitchens, hotels); self-employed hawkers and stallholders a substantial segment.',
    incomeStability: 'stable',
    gates: { minResidency: 'ep', licenceMonths: null, licence_note: 'No statutory licence. WSQ Food Safety Course Level 1 (1 day, about S$150) is mandatory for food handlers in SFA-licensed establishments; not a real gate. Written resident-worker case in sources.md: the PWM floor already prices in the policy environment; no separate levy/quota quarantine is modelled.' },
    gates_review_date: '2026-09-19',
    tags: ['meaning', 'hands-on', 'shifts', 'craft']
  },
  {
    id: 'logistics-planner',
    title: 'Logistics / production planner',
    entry_pay: 2240,
    settled_pay: 3283,
    pay_source: 'Entry: MOM Q1 2026 top entry-level PMET opportunities: "Logistics / production planner" gross S$2,800-3,500/month (low end used). Settled: MOM OW 2024 median gross S$4,104. Cash after 20% employee CPF. base-like; bonus extra.',
    wage_label: 'MOM entry-level PMET data, Q1 2026 / occupational wages, June 2024',
    reskill_list_price: 3800,
    subsidy_class: 'none',
    reskill_nett_base: 3800,
    reskill_nett_40plus: 3800,
    reskill_months: 12,
    reskill_source: 'SIMM Diploma in Logistics and Supply Chain Management, 12 months. S$3,800 member course fee plus materials, application and membership; no verified SSG age-based subsidy split, so both netts equal the list price; flagged in sources.md. reskill_months 12 reflects the diploma duration. Largely transferable skills; the diploma is the named pathway.',
    allowance: 0,
    hours_score: 75,
    hours_note: 'Standard office hours around 44h per week; some overtime in peak seasons (SPEC 8.1).',
    sovereignty_score: 65,
    sovereignty_note: 'Office-based, some hybrid depending on employer; fixed schedule, no shift work (SPEC 8.2).',
    meaning_score: 48,
    meaning_cite: 'Single-rater. Craft depth and autonomy 20/40 (planning and scheduling craft, moderate autonomy); purpose legibility 12/30 (keeping goods moving is moderately legible); variety and feedback 16/30 (varied orders and disruptions, schedule feedback). Human contact excluded from meaning per SPEC 8.3.',
    stability_score: 53,
    stability_cite: 'Single-rater. Demand stable 30 (steady hiring across manufacturers, 3PLs and retail; not a shortage occupation); automation medium 18 (planning software plus AI exposure; exception-handling stays human); moat open entry 5 (SPEC 8.4).',
    demand: 'stable',
    demand_date: '2026-09',
    automation_exposure: 'medium',
    automation_date: '2026-09',
    contract_mix: 'Almost entirely direct employment by manufacturers, 3PLs, distributors and retailers; mostly permanent.',
    incomeStability: 'stable',
    gates: { minResidency: 'ep', licenceMonths: null, licence_note: 'No licence, registration or citizenship requirement.' },
    gates_review_date: '2026-09-19',
    tags: ['stability', 'office', 'operations']
  },
  {
    id: 'compliance-officer',
    title: 'Compliance officer / risk analyst',
    entry_pay: 3200,
    settled_pay: 7582,
    pay_source: 'Entry: MOM Q1 2026 top entry-level PMET opportunities: "Compliance / risk analyst" gross S$4,000-5,600/month (low end used). Settled: MOM Occupational Wages 2025 median gross S$9,182. Cash = gross minus 20% of the first S$8,000 (ceiling-aware: S$9,182 - S$1,600 = S$7,582). base-like; bonus extra.',
    wage_label: 'MOM entry-level PMET data, Q1 2026 / occupational wages, 2025',
    reskill_list_price: 9504,
    subsidy_class: 'ibf-sts-70',
    reskill_nett_base: 2376,
    reskill_nett_40plus: 2376,
    reskill_months: 6,
    reskill_source: 'SUSS Graduate Certificate in Compliance (15 CU: FIN571, FIN573, FIN575), about 6 months. SUSS brochure (Jan 2026): tuition S$7,920 before GST for SC/SPR, S$9,504 before GST for other residents; IBF-STS funding up to 70% for eligible SC/SPR. Nett = 7,920 x 0.3 = S$2,376 (before GST; assumes full 70%; 40+ enhancement unverified so 40+ equals base). Admission expects a related bachelor\'s (Finance, Accountancy, Economics, Business, Law) or relevant experience case-by-case. reskill_months 6 reflects the programme duration.',
    allowance: 0,
    hours_score: 50,
    hours_note: 'Office 44-48h norm; regulatory deadlines and incident reviews create spikes (SPEC 8.1).',
    sovereignty_score: 65,
    sovereignty_note: 'Office-based with hybrid common in banks; fixed schedule, deadline-driven (SPEC 8.2).',
    meaning_score: 55,
    meaning_cite: 'Single-rater. Craft depth and autonomy 24/40 (regulatory craft, bounded autonomy); purpose legibility 15/30 (market-integrity purpose moderately legible); variety and feedback 16/30 (varied cases, review feedback). Human contact excluded from meaning per SPEC 8.3.',
    stability_score: 80,
    stability_cite: 'Single-rater. Demand growing 50 (MOM Job Vacancies 2025: among the most sought-after roles; MAS regulatory intensity durable); automation medium 18 (RegTech automates monitoring; judgement and accountability stay human); moat cert-gated 12 (IBF/ICA credentials voluntary but market-expected; SPEC 8.4).',
    demand: 'growing',
    demand_date: '2026-09',
    automation_exposure: 'medium',
    automation_date: '2026-09',
    contract_mix: 'Employed by banks, insurers, fintech firms and consultancies; contract roles common in banks.',
    incomeStability: 'stable',
    gates: { minResidency: 'ep', licenceMonths: null, licence_note: 'No statutory licence for most compliance roles. MAS licensing applies to specific regulated activities (e.g. fund management); not modelled as a universal gate.' },
    gates_review_date: '2026-09-19',
    tags: ['money', 'stability', 'office']
  },
  {
    id: 'training-professional',
    title: 'Training and staff development professional',
    entry_pay: 3592,
    settled_pay: 4768,
    pay_source: 'MOM Report on Occupational Wages 2024: "Training and staff development professional" median gross S$4,490; "Training manager" median gross S$5,960 (used as the settled band for the experienced tier). Cash after 20% employee CPF. base-like; bonus extra.',
    wage_label: 'MOM occupational wages, June 2024',
    reskill_list_price: 6322,
    subsidy_class: 'wsq-70-90',
    reskill_nett_base: 2149,
    reskill_nett_40plus: 989,
    reskill_months: 60,
    reskill_source: 'IAL Advanced Certificate in Learning and Performance (ACLP) 3.0, 71 hours. List S$6,322; S$2,149.48 after 70% funding; S$989.48 after 90% MCES (SC 40+) (subsidy-only; SkillsFuture Credit not subtracted). Requires 5 years of domain expertise to be credible as a trainer; the ACLP is the credential, domain experience is the de-facto gate. Time-to-employable for a true switcher is about 60 months (5 years domain); the 6-month ACLP is the course, not employability. F2 kills this role inside the v1 window.',
    allowance: 0,
    hours_score: 75,
    hours_note: 'Standard office hours around 44h; delivery schedules set the calendar (SPEC 8.1).',
    sovereignty_score: 65,
    sovereignty_note: 'Fixed delivery schedule; freelance trainers choose engagements (SPEC 8.2).',
    meaning_score: 70,
    meaning_cite: 'Single-rater. Craft depth and autonomy 28/40 (facilitation craft, session autonomy); purpose legibility 22/30 (learning outcomes are directly legible); variety and feedback 20/30 (varied cohorts, learner feedback). Human contact excluded from meaning per SPEC 8.3.',
    stability_score: 60,
    stability_cite: 'Single-rater. Demand stable 30 (corporate L&D steady; SkillsFuture ecosystem durable); automation medium 18 (e-learning and AI content tools; facilitation stays human); moat credential-gated 12 (ACLP plus domain expertise; SPEC 8.4).',
    demand: 'stable',
    demand_date: '2026-09',
    automation_exposure: 'medium',
    automation_date: '2026-09',
    contract_mix: 'Employed by corporates, training providers and the public sector; freelance trainers a meaningful segment.',
    incomeStability: 'stable',
    gates: { minResidency: 'ep', licenceMonths: null, licence_note: 'No statutory licence. De-facto gate: 5 years of domain expertise plus ACLP for credibility.' },
    gates_review_date: '2026-09-19',
    tags: ['meaning', 'office']
  },
  {
    id: 'systems-analyst',
    title: 'Systems analyst',
    entry_pay: 3200,
    settled_pay: 5573,
    pay_source: 'Entry: MOM Dec 2025 salary data for "Systems analyst": gross S$4,000/month (low end used). Settled: MOM OW 2024 "Systems designer / analyst" median gross S$6,966. Cash after 20% employee CPF. base-like; bonus extra.',
    wage_label: 'MOM salary data, Dec 2025 / occupational wages, June 2024',
    reskill_list_price: 11650,
    subsidy_class: 'sctp-70-90',
    reskill_nett_base: 4977,
    reskill_nett_40plus: 1933,
    reskill_months: 7,
    reskill_source: 'BELLS SCTP Full Stack Developer (TGS-2023021703), 231.5 classroom hours (about 5 months): the technical foundation for systems-analysis roles. Full fee S$11,650; provider post-70% S$4,976.94; provider post-90% MCES S$1,932.94 (subsidy-only; SkillsFuture Credit not subtracted). reskill_months 7 covers the course plus job search. Note: dedicated systems-analysis programmes were not verified; this is a software-development foundation pathway.',
    allowance: 0,
    hours_score: 50,
    hours_note: 'PMET 44-48h norm with project-deadline spikes (SPEC 8.1: office norm anchor).',
    sovereignty_score: 65,
    sovereignty_note: 'Hybrid common; project timelines set the schedule (SPEC 8.2).',
    meaning_score: 58,
    meaning_cite: 'Single-rater. Craft depth and autonomy 26/40 (analysis and design craft, moderate autonomy); purpose legibility 14/30 (system-improvement legibility, commercial purpose); variety and feedback 18/30 (varied systems, stakeholder feedback). Human contact excluded from meaning per SPEC 8.3.',
    stability_score: 73,
    stability_cite: 'Single-rater. Demand growing 50 (MOM Job Vacancies 2025: S$6,000-9,700 range signals strong demand); automation medium 18 (AI assists documentation and testing; requirements analysis stays human); moat open entry 5 (no licence or mandatory cert; SPEC 8.4).',
    card_note: 'Reskill is a software-dev foundation (BELLS SCTP), not a dedicated systems-analysis programme.',
    demand: 'growing',
    demand_date: '2026-09',
    automation_exposure: 'medium',
    automation_date: '2026-09',
    contract_mix: 'Employed by banks, government tech agencies, consultancies and large enterprises; contract roles common.',
    incomeStability: 'stable',
    gates: { minResidency: 'ep', licenceMonths: null, licence_note: 'No licence, registration or citizenship requirement. De-facto gate: technical foundation plus business-domain knowledge.' },
    gates_review_date: '2026-09-19',
    tags: ['money', 'stability', 'office', 'hybrid']
  }
];
if (typeof module !== 'undefined' && module.exports) { module.exports = ROLES15; }
