// Career Switch v2 role data.
// Generated from role-index-2026-09-20.json (priced=TRUE only, 115 roles).
// Regenerate with tools/build-roles-index-js.py after each Sheet export; never hand-edit.
const ROLES_INDEX = [
 {
  "id": "R001",
  "title": "Data analyst",
  "entry_pay": 4646,
  "settled_pay": 6765,
  "reskill_months": 6.0,
  "reskill_nett_base": 6300.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "data",
  "domain_adjacent": [
   "tech"
  ],
  "gate_type": "none",
  "gate_detail": "No licence/registration. De-facto gate: portfolio of analysis projects.",
  "pay_confidence": "high",
  "reskill_source": "MySkillsFuture TGS-2025052661; provider post-70% S$6300 (subsidy-only)",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R002",
  "title": "Software developer",
  "entry_pay": 5326,
  "settled_pay": 7287,
  "reskill_months": 7.0,
  "reskill_nett_base": 4977.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "tech",
  "domain_adjacent": [
   "data"
  ],
  "gate_type": "none",
  "gate_detail": "No licence/registration. De-facto gate: portfolio and technical interviews.",
  "pay_confidence": "high",
  "reskill_source": "bellstech.sg; provider post-70% S$4976.94 (subsidy-only)",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R003",
  "title": "Cybersecurity analyst",
  "entry_pay": 4300,
  "settled_pay": 6160,
  "reskill_months": 6.0,
  "reskill_nett_base": 5183.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "tech",
  "domain_adjacent": [
   "data"
  ],
  "gate_type": "none",
  "gate_detail": "No licence for commercial SOC roles. Some gov/defence postings need SC + clearance; narrow, not modelled.",
  "pay_confidence": "high",
  "reskill_source": "provider post-70% S$5182.95 (subsidy-only)",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R004",
  "title": "UX designer",
  "entry_pay": 4663,
  "settled_pay": 6306,
  "reskill_months": 7.0,
  "reskill_nett_base": 6148.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "design",
  "domain_adjacent": [
   "tech",
   "marketing"
  ],
  "gate_type": "none",
  "gate_detail": "No licence/registration. De-facto gate: portfolio of 2-3 case studies.",
  "pay_confidence": "med",
  "reskill_source": "NTU; provider post-70% S$6147.60 (subsidy-only)",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R005",
  "title": "Digital marketer",
  "entry_pay": 2943,
  "settled_pay": 4240,
  "reskill_months": 6.0,
  "reskill_nett_base": 4977.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "marketing",
  "domain_adjacent": [
   "design"
  ],
  "gate_type": "none",
  "gate_detail": "No licence/registration. De-facto gate: portfolio of campaign work.",
  "pay_confidence": "high",
  "reskill_source": "provider post-70% S$4976.94 (subsidy-only)",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R006",
  "title": "Accountant",
  "entry_pay": 3640,
  "settled_pay": 5360,
  "reskill_months": 9.0,
  "reskill_nett_base": 2000.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "finance",
  "domain_adjacent": [],
  "gate_type": "cert",
  "gate_detail": "No statutory licence for in-house/commercial roles. De-facto gate: relevant degree expected at entry; ACRA public-accountant registration binds audit partners only.",
  "pay_confidence": "med",
  "reskill_source": "ACCA official 2026 pricing; ~S$2000 total",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": "accountant",
   "gateMonths": 36
  }
 },
 {
  "id": "R007",
  "title": "HR executive",
  "entry_pay": 2240,
  "settled_pay": 3200,
  "reskill_months": 3.0,
  "reskill_nett_base": 425.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "people",
  "domain_adjacent": [],
  "gate_type": "none",
  "gate_detail": "No licence/registration. IHRP certification is voluntary.",
  "pay_confidence": "med",
  "reskill_source": "SHRI; post-70% SSG S$425 (subsidy-only); IHRP cert voluntary",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R008",
  "title": "Enrolled nurse",
  "entry_pay": 1640,
  "settled_pay": 2496,
  "reskill_months": 27.0,
  "reskill_nett_base": 0.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "healthcare",
  "domain_adjacent": [],
  "gate_type": "licence",
  "gate_detail": "CCP-EN requires SC or PR. SNB enrolment only on completion of 2yr SNB-approved programme. 2-year service bond with 2 sureties.",
  "pay_confidence": "med",
  "reskill_source": "MOH healthcare CCP FAQ; SNB programme requirements",
  "gates": {
   "minResidency": "pr"
  },
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": "nurse",
   "gateMonths": 27
  }
 },
 {
  "id": "R009",
  "title": "Electrician",
  "entry_pay": 1716,
  "settled_pay": 2400,
  "reskill_months": 24.0,
  "reskill_nett_base": 1252.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "trades",
  "domain_adjacent": [],
  "gate_type": "none",
  "gate_detail": "No licence to work under a licensed electrician. Full EMA Licensed Electrician ~48mo total, outside calculator window; settled pay is pre-licence tier.",
  "pay_confidence": "high",
  "reskill_source": "ITE AY2026 fee schedule; SC S$626/yr x2",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R010",
  "title": "Plumber",
  "entry_pay": 1200,
  "settled_pay": 2400,
  "reskill_months": 6.0,
  "reskill_nett_base": 2434.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "self-employed",
  "domain_primary": "trades",
  "domain_adjacent": [],
  "gate_type": "none",
  "gate_detail": null,
  "pay_confidence": "low",
  "reskill_source": "BCA Academy; post-70% S$2433.61 (subsidy-only)",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": "plumber",
   "gateMonths": 36
  }
 },
 {
  "id": "R011",
  "title": "Cook",
  "entry_pay": 1976,
  "settled_pay": 2016,
  "reskill_months": 18.0,
  "reskill_nett_base": 5968.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "hospitality",
  "domain_adjacent": [],
  "gate_type": "cert",
  "gate_detail": "SFA WSQ Food Safety Course Level 1 mandatory \u2014 SFA explicitly names cooks as food handlers (verified 2026-09-20).",
  "pay_confidence": "high",
  "reskill_source": "SHATEC; provider-derived list S$19893; nett ~S$5968",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R012",
  "title": "Logistics / production planner",
  "entry_pay": 2240,
  "settled_pay": 3283,
  "reskill_months": 12.0,
  "reskill_nett_base": 3800.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "ops",
  "domain_adjacent": [],
  "gate_type": "none",
  "gate_detail": "No licence, registration or citizenship requirement.",
  "pay_confidence": "med",
  "reskill_source": "SIMM; S$3800 member fee; no verified SSG age-based subsidy",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R013",
  "title": "Compliance officer / risk analyst",
  "entry_pay": 3200,
  "settled_pay": 7582,
  "reskill_months": 6.0,
  "reskill_nett_base": 7920.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "finance",
  "domain_adjacent": [],
  "gate_type": "none",
  "gate_detail": "No statutory licence for most compliance roles. MAS licensing applies to specific regulated activities (e.g. fund management); not universal.",
  "pay_confidence": "med",
  "reskill_source": "SUSS brochure Jan 2026: S$7920 SC/SPR before GST (S$9504 other residents)",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R014",
  "title": "Training and staff development professional",
  "entry_pay": 3592,
  "settled_pay": 4768,
  "reskill_months": 6.0,
  "reskill_nett_base": 2149.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "people",
  "domain_adjacent": [],
  "gate_type": "cert",
  "gate_detail": "No statutory licence. De-facto gate: 5 years of domain expertise plus ACLP for credibility.",
  "pay_confidence": "med",
  "reskill_source": "IAL; post-70% S$2149.48 (subsidy-only); post-90% MCES S$989.48",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R015",
  "title": "Systems analyst",
  "entry_pay": 3200,
  "settled_pay": 5573,
  "reskill_months": 7.0,
  "reskill_nett_base": 5000.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "tech",
  "domain_adjacent": [
   "data"
  ],
  "gate_type": "none",
  "gate_detail": "No licence, registration or citizenship requirement. De-facto gate: technical foundation plus business-domain knowledge.",
  "pay_confidence": "med",
  "reskill_source": "provider post-70% subsidy-only figure",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R020",
  "title": "Dental assistant",
  "entry_pay": 1840,
  "settled_pay": 2160,
  "reskill_months": 12.0,
  "reskill_nett_base": 0.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "healthcare",
  "domain_adjacent": [
   "people"
  ],
  "gate_type": "employer",
  "gate_detail": "Requires employment at a participating dental clinic; 2026 course fee S$6,540 (incl GST) is paid in full by the sponsoring employer",
  "pay_confidence": "med",
  "reskill_source": "http://sda.org.sg/wp-content/uploads/2026/02/19th-Batch-Nitec-in-Dental-Assisting-Invitation-2025-2026-Invitation-1.pdf",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R021",
  "title": "Optical assistant",
  "entry_pay": 1840,
  "settled_pay": 2240,
  "reskill_months": 4.5,
  "reskill_nett_base": 3013.2,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "healthcare",
  "domain_adjacent": [
   "people"
  ],
  "gate_type": "none",
  "gate_detail": "No statutory registration for optical assistants; only optometrists and opticians register with the Optometrists and Opticians Board",
  "pay_confidence": "med",
  "reskill_source": "https://courses.myskillsfuture.gov.sg/courses/TGS-2022015171--SCTP-WSQ-HIGHER-CERTIFICATE-HEALTHCARE-OPERATIONS-Eligible-FullTime-TA",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R022",
  "title": "Medical records officer",
  "entry_pay": 2152,
  "settled_pay": 2320,
  "reskill_months": 4.5,
  "reskill_nett_base": 3013.2,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "healthcare",
  "domain_adjacent": [
   "ops",
   "data"
  ],
  "gate_type": "none",
  "gate_detail": "No statutory registration for medical records officers in Singapore",
  "pay_confidence": "med",
  "reskill_source": "https://courses.myskillsfuture.gov.sg/courses/TGS-2022015171--SCTP-WSQ-HIGHER-CERTIFICATE-HEALTHCARE-OPERATIONS-Eligible-FullTime-TA",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R024",
  "title": "Nursing aide / aged-care assistant",
  "entry_pay": 1946,
  "settled_pay": 2400,
  "reskill_months": 5.0,
  "reskill_nett_base": 2500.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "healthcare",
  "domain_adjacent": [
   "people"
  ],
  "gate_type": "none",
  "gate_detail": null,
  "pay_confidence": "med",
  "reskill_source": "MySkillsFuture TGS-2024049369, TGS-2020505788, TGS-2024049471 (checked Sep 2026)",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R025",
  "title": "Home care assistant",
  "entry_pay": 1440,
  "settled_pay": 1760,
  "reskill_months": 0.03,
  "reskill_nett_base": 150.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "healthcare",
  "domain_adjacent": [
   "people"
  ],
  "gate_type": "none",
  "gate_detail": "No statutory registration; WSQ certificate plus employer training is the working gate",
  "pay_confidence": "med",
  "reskill_source": "https://courses.myskillsfuture.gov.sg/courses/TGS-2024050019--WSQ-Care-Assistance-Community-Care-Associate",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R026",
  "title": "Pharmacy assistant",
  "entry_pay": 1600,
  "settled_pay": 1920,
  "reskill_months": 12.0,
  "reskill_nett_base": 2952.5,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "healthcare",
  "domain_adjacent": [
   "people",
   "ops"
  ],
  "gate_type": "employer",
  "gate_detail": "Requires minimum 6 months experience as pharmacy assistant, clinic assistant or pharmacy technician (prescription processing/packing) plus full-time employment in a pharmacy or medical clinic at registration and throughout the course; upskilling route, not an entry route",
  "pay_confidence": "med",
  "reskill_source": "https://pss.org.sg/courses/wsq-advanced-certificate-in-healthcare-pharmacy-support/",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R027",
  "title": "Phlebotomist",
  "entry_pay": 1920,
  "settled_pay": 2400,
  "reskill_months": 0.1,
  "reskill_nett_base": 822.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "healthcare",
  "domain_adjacent": [
   "ops"
  ],
  "gate_type": "cert",
  "gate_detail": "Course competency certificate; no statutory registration for phlebotomists in Singapore",
  "pay_confidence": "med",
  "reskill_source": "https://www.csmacademy.edu.sg/doc/brochure/Phlebotomy_Brochure_160126.pdf",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R030",
  "title": "Health screening coordinator",
  "entry_pay": 2160,
  "settled_pay": 2720,
  "reskill_months": 4.5,
  "reskill_nett_base": 3013.2,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "healthcare",
  "domain_adjacent": [
   "people",
   "ops"
  ],
  "gate_type": "none",
  "gate_detail": "No statutory registration; health screening coordination is a frontline and administrative role",
  "pay_confidence": "med",
  "reskill_source": "https://courses.myskillsfuture.gov.sg/courses/TGS-2022015171--SCTP-WSQ-HIGHER-CERTIFICATE-HEALTHCARE-OPERATIONS-Eligible-FullTime-TA",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R033",
  "title": "Front office / guest relations officer",
  "entry_pay": 1800,
  "settled_pay": 2450,
  "reskill_months": 3.0,
  "reskill_nett_base": 0.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "hospitality",
  "domain_adjacent": [
   "people",
   "ops"
  ],
  "gate_type": "none",
  "gate_detail": "None identified",
  "pay_confidence": "med",
  "reskill_source": "WSG factsheet v7.0 (2022); 2026 availability unverified",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R034",
  "title": "Housekeeping supervisor",
  "entry_pay": 1900,
  "settled_pay": 2300,
  "reskill_months": 3.0,
  "reskill_nett_base": 0.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "hospitality",
  "domain_adjacent": [
   "ops",
   "people"
  ],
  "gate_type": "none",
  "gate_detail": "None identified",
  "pay_confidence": "med",
  "reskill_source": "WSG factsheet v5.0 (2022); 2026 availability unverified",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R036",
  "title": "Hotel operations executive",
  "entry_pay": 2250,
  "settled_pay": 3050,
  "reskill_months": 3.0,
  "reskill_nett_base": 0.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "hospitality",
  "domain_adjacent": [
   "ops"
  ],
  "gate_type": "none",
  "gate_detail": "None identified",
  "pay_confidence": "med",
  "reskill_source": "WSG factsheet v7.0 (2022); 2026 availability unverified",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R037",
  "title": "Hotel concierge",
  "entry_pay": 2060,
  "settled_pay": 2400,
  "reskill_months": 0.0,
  "reskill_nett_base": 0.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "hospitality",
  "domain_adjacent": [
   "people"
  ],
  "gate_type": "none",
  "gate_detail": "No licence or cert; de-facto gate is guest-service experience (luxury hotels prefer 1 yr front-office/concierge exp)",
  "pay_confidence": "med",
  "reskill_source": "None",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R039",
  "title": "Reservations executive",
  "entry_pay": 2160,
  "settled_pay": 2720,
  "reskill_months": 0.0,
  "reskill_nett_base": 0.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "hospitality",
  "domain_adjacent": [
   "ops",
   "tech"
  ],
  "gate_type": "none",
  "gate_detail": "No licence or cert; de-facto gate is customer-service/phone background + MS Office",
  "pay_confidence": "med",
  "reskill_source": "None",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R040",
  "title": "Room attendant",
  "entry_pay": 1280,
  "settled_pay": 1560,
  "reskill_months": 0.0,
  "reskill_nett_base": 0.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "hospitality",
  "domain_adjacent": [
   "ops"
  ],
  "gate_type": "none",
  "gate_detail": "No licence or cert; de-facto gate is physical fitness and basic English",
  "pay_confidence": "high",
  "reskill_source": "None",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R041",
  "title": "Bell attendant",
  "entry_pay": 1660,
  "settled_pay": 1800,
  "reskill_months": 0.0,
  "reskill_nett_base": 0.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "hospitality",
  "domain_adjacent": [
   "people"
  ],
  "gate_type": "none",
  "gate_detail": "None \u2014 bell attendants handle luggage, not food/beverages, so no SFA certification required",
  "pay_confidence": "med",
  "reskill_source": "None",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R042",
  "title": "Barista",
  "entry_pay": 1120,
  "settled_pay": 1651,
  "reskill_months": 0.0,
  "reskill_nett_base": 40.5,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "hospitality",
  "domain_adjacent": [
   "people"
  ],
  "gate_type": "cert",
  "gate_detail": "SFA WSQ Food Safety Course Level 1 mandatory \u2014 baristas handle/prepare beverages in SFA-licensed establishments",
  "pay_confidence": "high",
  "reskill_source": "TGS-2025054086; https://jacinlearning.com/courses/food-safety-course-singapore",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R043",
  "title": "Waiter",
  "entry_pay": 1856,
  "settled_pay": 1968,
  "reskill_months": 2.0,
  "reskill_nett_base": 0.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "hospitality",
  "domain_adjacent": [
   "people"
  ],
  "gate_type": "none",
  "gate_detail": null,
  "pay_confidence": "high",
  "reskill_source": "Food Services PWM training requirement (MOM PWM page)",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R045",
  "title": "Food service counter attendant",
  "entry_pay": 1836,
  "settled_pay": 1948,
  "reskill_months": 2.0,
  "reskill_nett_base": 0.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "hospitality",
  "domain_adjacent": [
   "people",
   "ops"
  ],
  "gate_type": "none",
  "gate_detail": null,
  "pay_confidence": "high",
  "reskill_source": "Food Services PWM training requirement (MOM PWM page)",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R047",
  "title": "Bartender",
  "entry_pay": 2000,
  "settled_pay": 2381,
  "reskill_months": 0.0,
  "reskill_nett_base": 40.5,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "hospitality",
  "domain_adjacent": [
   "people"
  ],
  "gate_type": "cert",
  "gate_detail": "SFA WSQ Food Safety Course Level 1 mandatory \u2014 SFA explicitly lists bartenders and mixologists as food handlers",
  "pay_confidence": "high",
  "reskill_source": "TGS-2025054086; https://jacinlearning.com/courses/food-safety-course-singapore",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R048",
  "title": "Commis chef",
  "entry_pay": 2142,
  "settled_pay": 2740,
  "reskill_months": 0.0,
  "reskill_nett_base": 0.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "hospitality",
  "domain_adjacent": [
   "ops"
  ],
  "gate_type": "cert",
  "gate_detail": "SFA Food Safety Course Level 1 mandatory for persons engaged in sale or preparation of food in licensed establishments",
  "pay_confidence": "high",
  "reskill_source": "None",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R051",
  "title": "Banquet / events coordinator",
  "entry_pay": 2160,
  "settled_pay": 2720,
  "reskill_months": 0.0,
  "reskill_nett_base": 0.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "hospitality",
  "domain_adjacent": [
   "people",
   "ops"
  ],
  "gate_type": "none",
  "gate_detail": "No statutory licence or mandatory certification; SFA Food Safety Course Level 1 applies only if the role involves sale or preparation of food (atypical for coordinators)",
  "pay_confidence": "med",
  "reskill_source": "None",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R052",
  "title": "Procurement executive",
  "entry_pay": 2400,
  "settled_pay": 3200,
  "reskill_months": 10.0,
  "reskill_nett_base": 3600.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "ops",
  "domain_adjacent": [
   "ops"
  ],
  "gate_type": "none",
  "gate_detail": "No statutory licence for procurement roles in Singapore; CIPS Level 4 is the employer-recognised professional credential.",
  "pay_confidence": "med",
  "reskill_source": "https://advancescs.com/cips-diploma-procurement-supply/",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R053",
  "title": "Buyer",
  "entry_pay": 2886,
  "settled_pay": 3755,
  "reskill_months": 3.0,
  "reskill_nett_base": 1030.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "ops",
  "domain_adjacent": [
   "ops"
  ],
  "gate_type": "none",
  "gate_detail": "No statutory requirement; SIMM states the programme is for newly appointed buyers and purchasing personnel; SIMM membership is compulsory.",
  "pay_confidence": "high",
  "reskill_source": "https://simm.org.sg/LSC/Certs/CPM.pdf",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R054",
  "title": "Procurement clerk",
  "entry_pay": 1900,
  "settled_pay": 2280,
  "reskill_months": 1.0,
  "reskill_nett_base": 460.2,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "ops",
  "domain_adjacent": [
   "ops"
  ],
  "gate_type": "none",
  "gate_detail": "No statutory requirement; course covers purchase administration: RFQ, PO creation and follow-up, goods receipt, supplier billing.",
  "pay_confidence": "med",
  "reskill_source": "http://www.ntuclearninghub.com/en-gb/-/course/wsq-effective-order-fulfilment",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R055",
  "title": "Supply-chain analyst",
  "entry_pay": 3200,
  "settled_pay": 4800,
  "reskill_months": 1.0,
  "reskill_nett_base": 472.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "ops",
  "domain_adjacent": [
   "ops",
   "data"
  ],
  "gate_type": "none",
  "gate_detail": "No statutory requirement; a Power BI analytics portfolio is the employer-recognised proof of skill for analyst roles.",
  "pay_confidence": "med",
  "reskill_source": "https://www.tertiarycourses.com.sg/media/courses/brochures/TGS-2020505444-SG.pdf?v=1780045494",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R056",
  "title": "Inventory controller",
  "entry_pay": 2400,
  "settled_pay": 2850,
  "reskill_months": 1.0,
  "reskill_nett_base": 501.5,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "ops",
  "domain_adjacent": [
   "ops"
  ],
  "gate_type": "none",
  "gate_detail": "No statutory requirement; stated audience is inventory and warehouse managers, senior logistics coordinators, distribution operations personnel.",
  "pay_confidence": "med",
  "reskill_source": "https://www.ntuclearninghub.com/en-gb/-/course/wsq-inventory-management",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R057",
  "title": "Stock records clerk",
  "entry_pay": 1560,
  "settled_pay": 2173,
  "reskill_months": 1.0,
  "reskill_nett_base": 212.4,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "ops",
  "domain_adjacent": [
   "ops"
  ],
  "gate_type": "none",
  "gate_detail": "No statutory requirement; stated as suitable for stock controllers, warehouse operators and backroom staff.",
  "pay_confidence": "high",
  "reskill_source": "http://www.ntuclearninghub.com/en-gb/-/course/wsq-perform-stock-control-housekeeping-operations",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R058",
  "title": "Storekeeper",
  "entry_pay": 1600,
  "settled_pay": 2000,
  "reskill_months": 1.0,
  "reskill_nett_base": 212.4,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "ops",
  "domain_adjacent": [
   "ops"
  ],
  "gate_type": "none",
  "gate_detail": "No statutory requirement; stated as suitable for stock controllers, warehouse operators and administrative staff.",
  "pay_confidence": "high",
  "reskill_source": "http://www.ntuclearninghub.com/en-gb/-/course/wsq-perform-warehouse-operations",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R059",
  "title": "Logistics coordinator",
  "entry_pay": 2000,
  "settled_pay": 2400,
  "reskill_months": 1.0,
  "reskill_nett_base": 590.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "ops",
  "domain_adjacent": [
   "ops"
  ],
  "gate_type": "none",
  "gate_detail": "No statutory requirement; stated audience explicitly lists logistics coordinators, supply chain executives and warehouse supervisors.",
  "pay_confidence": "med",
  "reskill_source": "http://www.ntuclearninghub.com/en-gb/-/course/effective-logistics-operations",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R060",
  "title": "Warehouse / fulfilment supervisor",
  "entry_pay": 2240,
  "settled_pay": 3200,
  "reskill_months": 1.0,
  "reskill_nett_base": 590.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "ops",
  "domain_adjacent": [
   "ops"
  ],
  "gate_type": "none",
  "gate_detail": "No statutory requirement; stated audience explicitly lists warehouse supervisors; covers logistics KPIs, risk management and best practices.",
  "pay_confidence": "med",
  "reskill_source": "http://www.ntuclearninghub.com/en-gb/-/course/effective-logistics-operations",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R061",
  "title": "Warehouse worker",
  "entry_pay": 1656,
  "settled_pay": 1966,
  "reskill_months": 1.0,
  "reskill_nett_base": 212.4,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "ops",
  "domain_adjacent": [
   "ops"
  ],
  "gate_type": "none",
  "gate_detail": "No statutory requirement; same course as R058, suitable for warehouse operators.",
  "pay_confidence": "high",
  "reskill_source": "http://www.ntuclearninghub.com/en-gb/-/course/wsq-perform-warehouse-operations",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R062",
  "title": "Operations executive",
  "entry_pay": 2400,
  "settled_pay": 3200,
  "reskill_months": 1.0,
  "reskill_nett_base": 500.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "ops",
  "domain_adjacent": [
   "ops"
  ],
  "gate_type": "none",
  "gate_detail": "No statutory requirement; provider lists Operations executive among the occupations the unit is relevant to.",
  "pay_confidence": "med",
  "reskill_source": "http://learnershub.com/courses/six-sigma-program/lean-sigma (2026 intakes to Dec 2026; self-sponsored SG/PR 21+ S$500)",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R063",
  "title": "Road transport operations officer",
  "entry_pay": 3100,
  "settled_pay": 3606,
  "reskill_months": 3.0,
  "reskill_nett_base": 1136.92,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "ops",
  "domain_adjacent": [
   "ops"
  ],
  "gate_type": "none",
  "gate_detail": "Class 4 is a Traffic Police licence for heavy vehicles; it is NOT a statutory requirement for the office-based operations role, but is the standard operational credential valued by employers.",
  "pay_confidence": "high",
  "reskill_source": "https://pcdcpl.com.sg/outline-fees/",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R064",
  "title": "Fleet / transport executive",
  "entry_pay": 2400,
  "settled_pay": 2800,
  "reskill_months": 1.0,
  "reskill_nett_base": 354.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "ops",
  "domain_adjacent": [
   "ops"
  ],
  "gate_type": "none",
  "gate_detail": "No statutory requirement; stated audience explicitly lists transport and fleet coordinators and staff transitioning from delivery ops to planning roles; 1 year of work experience is an entry condition.",
  "pay_confidence": "med",
  "reskill_source": "http://www.ntuclearninghub.com/en-gb/-/course/wsq-traffic-management-in-logistics-industry",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R065",
  "title": "Facilities coordinator",
  "entry_pay": 2000,
  "settled_pay": 2400,
  "reskill_months": 1.0,
  "reskill_nett_base": 885.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "ops",
  "domain_adjacent": [
   "trades"
  ],
  "gate_type": "none",
  "gate_detail": "No statutory licence for facilities coordinator roles; digital FM systems are the employer-recognised skill.",
  "pay_confidence": "med",
  "reskill_source": "https://www.tertiarycourses.com.sg/media/courses/brochures/TGS-2024045800-SG.pdf?v=1780045544",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R066",
  "title": "Facilities manager",
  "entry_pay": 3600,
  "settled_pay": 5232,
  "reskill_months": 1.0,
  "reskill_nett_base": 319.48,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "ops",
  "domain_adjacent": [
   "trades"
  ],
  "gate_type": "none",
  "gate_detail": "No statutory licence for facilities managers in Singapore; BCA Academy is the built-environment sector training arm; IFMA FMP (US$1,850 member / US$2,150 standard) is the international alternative, not converted to SGD here.",
  "pay_confidence": "med",
  "reskill_source": "https://www.bcaa.edu.sg/what-we-offer/courses/Details/principles-and-application-of-integrated-facilities-management",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R067",
  "title": "QA / QC inspector",
  "entry_pay": 2000,
  "settled_pay": 3434,
  "reskill_months": 1.0,
  "reskill_nett_base": 472.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "ops",
  "domain_adjacent": [
   "trades"
  ],
  "gate_type": "none",
  "gate_detail": "No statutory licence for QA/QC inspectors; ISO 9001 fundamentals is the employer-recognised entry credential.",
  "pay_confidence": "med",
  "reskill_source": "https://www.tertiarycourses.com.sg/media/courses/brochures/TGS-2023020563-SG.pdf?v=1780045517",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R070",
  "title": "Security officer",
  "entry_pay": 2472,
  "settled_pay": 2712,
  "reskill_months": 0.5,
  "reskill_nett_base": 459.3,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "trades",
  "domain_adjacent": [
   "ops"
  ],
  "gate_type": "licence",
  "gate_detail": "PLRD security-officer licence (GoBusiness, S$16, valid 5 yrs): 3 enhanced WSQ Basic Licensing Units (Guard & Patrol + Basic Security Equipment, Security Incidents & Services, Terrorist Threats).",
  "pay_confidence": "high",
  "reskill_source": "https://www.acuity.com.sg/wp-content/uploads/2026/06/AcuityAcademyCourseFee2026.pdf (2026 price list, SG 21-39 nett incl GST: S$156.00 + S$153.62 + S$149.68)",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R073",
  "title": "Waste collection crew",
  "entry_pay": 2272,
  "settled_pay": 2592,
  "reskill_months": 0.25,
  "reskill_nett_base": 696.2,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "trades",
  "domain_adjacent": [
   "trades"
  ],
  "gate_type": "cert",
  "gate_detail": "NEA PWM: min 2 WSQ waste-management modules for crew",
  "pay_confidence": "med",
  "reskill_source": "workwork.sg/waste-management-courses-level-1 (full fees S$850.20 + S$436.00 incl GST); NEA GWDF PWM briefing slides",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R074",
  "title": "Waste collection supervisor",
  "entry_pay": 2592,
  "settled_pay": 2792,
  "reskill_months": 0.25,
  "reskill_nett_base": 1357.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "trades",
  "domain_adjacent": [
   "trades"
  ],
  "gate_type": "cert",
  "gate_detail": "NEA PWM: min 4 cumulative WSQ modules for waste collection supervisor",
  "pay_confidence": "med",
  "reskill_source": "workwork.sg/waste-management-courses-level-1 and /waste-management-courses-level-2 (full fees sum S$2,507.00 incl GST); NEA GWDF PWM briefing slides",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R075",
  "title": "Waste collection driver",
  "entry_pay": 2592,
  "settled_pay": 2832,
  "reskill_months": 3.0,
  "reskill_nett_base": 2281.52,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "trades",
  "domain_adjacent": [
   "trades"
  ],
  "gate_type": "licence",
  "gate_detail": "Class 4 driving licence (statutory, via driving centre + Traffic Police test); NEA PWM min 3 WSQ modules for driver",
  "pay_confidence": "med",
  "reskill_source": "pcdcpl.com.sg/outline-fees (Class 4 package S$1,136.92 all-in, 1st attempt off-peak); workwork.sg (3 modules full fees S$2,114.60 incl GST)",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R076",
  "title": "Materials recovery sorter",
  "entry_pay": 2192,
  "settled_pay": 2512,
  "reskill_months": 0.25,
  "reskill_nett_base": 696.2,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "trades",
  "domain_adjacent": [
   "trades"
  ],
  "gate_type": "cert",
  "gate_detail": "NEA PWM: min 2 WSQ modules for materials-recovery sorter",
  "pay_confidence": "med",
  "reskill_source": "workwork.sg/waste-management-courses-level-1 (full fees S$436.00 + S$850.20 incl GST); NEA GWDF PWM briefing slides",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R077",
  "title": "Materials recovery plant supervisor",
  "entry_pay": 2512,
  "settled_pay": 2672,
  "reskill_months": 0.25,
  "reskill_nett_base": 1475.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "trades",
  "domain_adjacent": [
   "trades"
  ],
  "gate_type": "cert",
  "gate_detail": "NEA PWM: min 4 cumulative WSQ modules for materials-recovery plant supervisor",
  "pay_confidence": "med",
  "reskill_source": "workwork.sg/waste-management-courses-level-1 and /waste-management-courses-level-2 (full fees sum S$2,725.00 incl GST); NEA GWDF PWM briefing slides",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R079",
  "title": "Multi-skilled cleaner / machine operator",
  "entry_pay": 2160,
  "settled_pay": 2296,
  "reskill_months": 2.0,
  "reskill_nett_base": 0.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "trades",
  "domain_adjacent": [
   "ops"
  ],
  "gate_type": "none",
  "gate_detail": null,
  "pay_confidence": "med",
  "reskill_source": "MOM Cleaning PWM training requirement",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R081",
  "title": "Air-con technician",
  "entry_pay": 1980,
  "settled_pay": 2610,
  "reskill_months": 0.25,
  "reskill_nett_base": 171.1,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "trades",
  "domain_adjacent": [
   "ops"
  ],
  "gate_type": "cert",
  "gate_detail": "WSQ Statement of Attainment (foundation); no statutory air-con technician licence in SG",
  "pay_confidence": "high",
  "reskill_source": "coursemology.sg/course/basic-aircon-maintenance-for-everyone (S$171.10 for under-40)",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R082",
  "title": "Automotive technician",
  "entry_pay": 1728,
  "settled_pay": 2221,
  "reskill_months": 0.25,
  "reskill_nett_base": 153.4,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "trades",
  "domain_adjacent": [
   "trades"
  ],
  "gate_type": "cert",
  "gate_detail": "WSQ Statement of Attainment; no statutory licence; trade competence via workshop apprenticeship",
  "pay_confidence": "high",
  "reskill_source": "coursemology.sg/course/basic-car-maintenance-class (S$153.40 for SG 21-39 after subsidy; page price table reverses age bands, course-details section verified against 50%/70% SSG subsidy math)",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R083",
  "title": "Automotive mechanic",
  "entry_pay": 1728,
  "settled_pay": 2221,
  "reskill_months": 0.25,
  "reskill_nett_base": 153.4,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "trades",
  "domain_adjacent": [
   "trades"
  ],
  "gate_type": "cert",
  "gate_detail": "WSQ Statement of Attainment; no statutory licence; trade competence via workshop apprenticeship",
  "pay_confidence": "high",
  "reskill_source": "coursemology.sg/course/basic-car-maintenance-class (S$153.40 for SG 21-39 after subsidy)",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R084",
  "title": "Building maintenance technician",
  "entry_pay": 2300,
  "settled_pay": 2898,
  "reskill_months": 3.0,
  "reskill_nett_base": 1301.79,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "trades",
  "domain_adjacent": [
   "ops"
  ],
  "gate_type": "cert",
  "gate_detail": "BCA Academy certificate; no statutory licence for general building maintenance technician",
  "pay_confidence": "med",
  "reskill_source": "bcaa.edu.sg course page (S$1,301.79 after 50% support for under-40)",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R088",
  "title": "Pest control technician",
  "entry_pay": 1600,
  "settled_pay": 1840,
  "reskill_months": 2.5,
  "reskill_nett_base": 253.36,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "trades",
  "domain_adjacent": [
   "trades"
  ],
  "gate_type": "licence",
  "gate_detail": "NEA Vector Control Technician Licence (full); application fee S$31 from 1 Apr 2026",
  "pay_confidence": "med",
  "reskill_source": "ITE/NEA pest-management brochure Apr-2025 (nett SC/PR fee S$222.36 incl GST); gobusiness.gov.sg (licence fee S$31 from 1 Apr 2026)",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R089",
  "title": "Forklift operator",
  "entry_pay": 1446,
  "settled_pay": 2000,
  "reskill_months": 0.25,
  "reskill_nett_base": 295.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "trades",
  "domain_adjacent": [
   "ops"
  ],
  "gate_type": "cert",
  "gate_detail": "WSQ Operate Forklift e-certificate (workplace competency; not an LTA road-driving licence). Refresher recommended every 3 years.",
  "pay_confidence": "high",
  "reskill_source": "galmon.com/training/forklift-course-training (full fee S$545 incl GST)",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R090",
  "title": "Cloud Infrastructure Engineer",
  "entry_pay": 4120,
  "settled_pay": 6066,
  "reskill_months": 6.0,
  "reskill_nett_base": 500.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "tech",
  "domain_adjacent": [],
  "gate_type": "none",
  "gate_detail": null,
  "pay_confidence": "med",
  "reskill_source": "AWS official; Tertiary Infotech Academy",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R091",
  "title": "DevOps Engineer",
  "entry_pay": 4800,
  "settled_pay": 6800,
  "reskill_months": 6.0,
  "reskill_nett_base": 500.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "tech",
  "domain_adjacent": [],
  "gate_type": "none",
  "gate_detail": null,
  "pay_confidence": "med",
  "reskill_source": "AWS official; Tertiary Infotech Academy",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R092",
  "title": "Network Engineer",
  "entry_pay": 3600,
  "settled_pay": 5440,
  "reskill_months": 1.0,
  "reskill_nett_base": 1180.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "tech",
  "domain_adjacent": [],
  "gate_type": "cert",
  "gate_detail": "Vendor cert (Network+) preferred by employers; no licence",
  "pay_confidence": "med",
  "reskill_source": "SSG course listing; Tertiary Infotech Academy",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R093",
  "title": "IT Support / Helpdesk Specialist",
  "entry_pay": 2400,
  "settled_pay": 3600,
  "reskill_months": 0.25,
  "reskill_nett_base": 1180.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "tech",
  "domain_adjacent": [],
  "gate_type": "none",
  "gate_detail": null,
  "pay_confidence": "med",
  "reskill_source": "SSG course listing; SkillsFuture Credit-eligible",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R100",
  "title": "Low-code Developer",
  "entry_pay": 4400,
  "settled_pay": 5600,
  "reskill_months": 3.0,
  "reskill_nett_base": 590.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "tech",
  "domain_adjacent": [],
  "gate_type": "cert",
  "gate_detail": "Vendor cert (PL-100) preferred; no licence",
  "pay_confidence": "med",
  "reskill_source": "Microsoft Learn; Tertiary Infotech Academy",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R101",
  "title": "RPA Developer",
  "entry_pay": 4400,
  "settled_pay": 5200,
  "reskill_months": 3.0,
  "reskill_nett_base": 0.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "tech",
  "domain_adjacent": [],
  "gate_type": "cert",
  "gate_detail": "Vendor cert preferred by employers; no licence",
  "pay_confidence": "med",
  "reskill_source": "UiPath Academy; Credly",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R111",
  "title": "Database Administrator",
  "entry_pay": 4400,
  "settled_pay": 5370,
  "reskill_months": 4.0,
  "reskill_nett_base": 1180.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "data",
  "domain_adjacent": [],
  "gate_type": "cert",
  "gate_detail": "Vendor cert preferred; no licence",
  "pay_confidence": "med",
  "reskill_source": "SSG course listing; Tertiary Infotech Academy",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R112",
  "title": "BI Developer",
  "entry_pay": 4400,
  "settled_pay": 6000,
  "reskill_months": 3.0,
  "reskill_nett_base": 2453.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "data",
  "domain_adjacent": [],
  "gate_type": "none",
  "gate_detail": null,
  "pay_confidence": "med",
  "reskill_source": "NTU PACE (S$8,175 full fee; S$2,452.50 after 70% funding, S$952.50 after 90%)",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R113",
  "title": "Analytics Engineer",
  "entry_pay": 4400,
  "settled_pay": 5264,
  "reskill_months": 6.0,
  "reskill_nett_base": 268.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "data",
  "domain_adjacent": [],
  "gate_type": "cert",
  "gate_detail": "No mandatory prerequisites, but dbt Labs recommends SQL proficiency plus 6+ months working in dbt; a newcomer needs a portfolio of dbt projects to be hirable",
  "pay_confidence": "med",
  "reskill_source": "https://www.getdbt.com/certifications/analytics-engineer-certification-exam",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R115",
  "title": "Operations Research Analyst",
  "entry_pay": 3808,
  "settled_pay": 5082,
  "reskill_months": 24.0,
  "reskill_nett_base": 62348.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "data",
  "domain_adjacent": [],
  "gate_type": "none",
  "gate_detail": "No licence or standard vendor cert for OR analysts; employers screen on a quantitative postgraduate degree (math/stats/OR/analytics)",
  "pay_confidence": "high",
  "reskill_source": "https://www.ntu.edu.sg/spms/about-us/mathematics/grad/msc-in-analytics",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R116",
  "title": "Database Architect",
  "entry_pay": 6400,
  "settled_pay": 8922,
  "reskill_months": 4.0,
  "reskill_nett_base": 1180.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "data",
  "domain_adjacent": [],
  "gate_type": "cert",
  "gate_detail": "Vendor cert preferred; no licence",
  "pay_confidence": "med",
  "reskill_source": "SSG course listing; Tertiary Infotech Academy",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R117",
  "title": "Graphic designer",
  "entry_pay": 2408,
  "settled_pay": 3012,
  "reskill_months": 3.0,
  "reskill_nett_base": 708.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "design",
  "domain_adjacent": [
   "marketing"
  ],
  "gate_type": "portfolio",
  "gate_detail": "Portfolio of 6-10 pieces (illustration, mood boards, print/digital applications); employers ask for portfolio with the application",
  "pay_confidence": "high",
  "reskill_source": "https://www.tertiarycourses.com.sg/media/courses/brochures/TGS-2023037829-SG.pdf",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R118",
  "title": "Interior designer",
  "entry_pay": 2744,
  "settled_pay": 3760,
  "reskill_months": 18.0,
  "reskill_nett_base": 11940.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "design",
  "domain_adjacent": [
   "trades"
  ],
  "gate_type": "cert",
  "gate_detail": "Diploma in interior design is the standard entry credential employers expect; no statutory licence in SG",
  "pay_confidence": "high",
  "reskill_source": "https://idis.edu.sg/courses/diploma-in-interior-design-2/",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R119",
  "title": "Motion designer / video editor",
  "entry_pay": 2400,
  "settled_pay": 3840,
  "reskill_months": 6.0,
  "reskill_nett_base": 256.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "design",
  "domain_adjacent": [
   "marketing"
  ],
  "gate_type": "none",
  "gate_detail": "No licence/registration. De-facto gate: showreel/portfolio.",
  "pay_confidence": "med",
  "reskill_source": "MySkillsFuture listing (crawled Sep 2026); ~S$256 payable after SkillsFuture funding",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R120",
  "title": "Brand designer",
  "entry_pay": 2408,
  "settled_pay": 3012,
  "reskill_months": 6.0,
  "reskill_nett_base": 0.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "design",
  "domain_adjacent": [
   "marketing"
  ],
  "gate_type": "portfolio",
  "gate_detail": "5-8 brand identity pieces (logos, brand systems, guidelines); 2-3 yrs experience typical",
  "pay_confidence": "high",
  "reskill_source": "https://cultjobs.com/job/studio-dam-singapore-full-time-brand-designer/",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R121",
  "title": "Packaging designer",
  "entry_pay": 2408,
  "settled_pay": 3012,
  "reskill_months": 6.0,
  "reskill_nett_base": 0.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "design",
  "domain_adjacent": [
   "marketing"
  ],
  "gate_type": "portfolio",
  "gate_detail": "Portfolio of packaging mockups, print-ready artwork and dielines; Adobe Illustrator proficiency",
  "pay_confidence": "high",
  "reskill_source": "https://www.jobzmall.com/careers/packaging-designer/faqs",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R122",
  "title": "3D designer / artist",
  "entry_pay": 3598,
  "settled_pay": 4255,
  "reskill_months": 3.0,
  "reskill_nett_base": 413.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "design",
  "domain_adjacent": [
   "tech"
  ],
  "gate_type": "portfolio",
  "gate_detail": "3D portfolio of modelled, textured and rendered pieces (character, object or archviz)",
  "pay_confidence": "high",
  "reskill_source": "https://www.tertiarycourses.com.sg/media/courses/brochures/TGS-2022015368-SG.pdf",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R123",
  "title": "Industrial / product designer",
  "entry_pay": 2240,
  "settled_pay": 3800,
  "reskill_months": 3.0,
  "reskill_nett_base": 401.2,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "design",
  "domain_adjacent": [
   "ops"
  ],
  "gate_type": "portfolio",
  "gate_detail": "Portfolio of CAD product concepts, renders and technical drawings",
  "pay_confidence": "med",
  "reskill_source": "https://www.tertiarycourses.com.sg/media/courses/brochures/TGS-2021005540-SG.pdf",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R124",
  "title": "Multimedia artist / animator",
  "entry_pay": 3598,
  "settled_pay": 4255,
  "reskill_months": 6.0,
  "reskill_nett_base": 424.8,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "design",
  "domain_adjacent": [
   "marketing"
  ],
  "gate_type": "portfolio",
  "gate_detail": "Demo reel of motion graphics/animation work (60-90 seconds)",
  "pay_confidence": "high",
  "reskill_source": "https://www.tertiarycourses.com.sg/media/courses/brochures/TGS-2022014982-SG.pdf",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R125",
  "title": "Web designer",
  "entry_pay": 4730,
  "settled_pay": 6306,
  "reskill_months": 3.0,
  "reskill_nett_base": 442.5,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "design",
  "domain_adjacent": [
   "tech"
  ],
  "gate_type": "portfolio",
  "gate_detail": "Portfolio of 3-5 live responsive websites (themes, plugins, content management)",
  "pay_confidence": "high",
  "reskill_source": "https://www.trainingint.com/wsq-wordpress-web-design-course",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R127",
  "title": "Visual merchandiser",
  "entry_pay": 2891,
  "settled_pay": 3789,
  "reskill_months": 1.0,
  "reskill_nett_base": 259.6,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "design",
  "domain_adjacent": [
   "marketing"
  ],
  "gate_type": "none",
  "gate_detail": "No licence or cert required; the WSQ SOA plus retail experience strengthens applications",
  "pay_confidence": "high",
  "reskill_source": "https://www.ntuclearninghub.com/en-gb/-/course/wsq-visual-merchandising-presentation-handle-merch-display-",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R128",
  "title": "Photographer",
  "entry_pay": 2796,
  "settled_pay": 4096,
  "reskill_months": 6.0,
  "reskill_nett_base": 472.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "design",
  "domain_adjacent": [
   "marketing"
  ],
  "gate_type": "portfolio",
  "gate_detail": "Portfolio of 30-50 strong images across portrait/product/event work; clients hire on portfolio alone",
  "pay_confidence": "high",
  "reskill_source": "https://cdn.prod.website-files.com/69a817c94060f9d4bfb1c760/6a022e0aacd50e37630495fe_Photography.pdf",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R134",
  "title": "Marketing communications specialist",
  "entry_pay": 2400,
  "settled_pay": 3440,
  "reskill_months": 6.0,
  "reskill_nett_base": 376.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "marketing",
  "domain_adjacent": [
   "design"
  ],
  "gate_type": "none",
  "gate_detail": "Experience-gated: hiring runs on comms/campaign track record; cert is supporting, not a requirement",
  "pay_confidence": "med",
  "reskill_source": "https://www.coursera.org/professional-certificates/google-digital-marketing-ecommerce",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R135",
  "title": "CRM / lifecycle marketer",
  "entry_pay": 2943,
  "settled_pay": 4240,
  "reskill_months": 0.0,
  "reskill_nett_base": 0.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "marketing",
  "domain_adjacent": [
   "data"
  ],
  "gate_type": "cert",
  "gate_detail": "No hard cert gate for hiring; HubSpot Email Marketing Certification is the credible free recognized route (valid 2 years) plus a portfolio of email flows/lifecycle campaigns",
  "pay_confidence": "high",
  "reskill_source": "https://www.createmycontent.co.uk/resources/hubspot/email-marketing-free-certification-course-hubspot",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R136",
  "title": "Copywriter",
  "entry_pay": 3462,
  "settled_pay": 4200,
  "reskill_months": 3.0,
  "reskill_nett_base": 0.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "marketing",
  "domain_adjacent": [
   "design"
  ],
  "gate_type": "portfolio",
  "gate_detail": "Hiring gates on writing samples; no particular degree or certification required",
  "pay_confidence": "high",
  "reskill_source": "https://shopify.com/uk/blog/how-to-become-a-copywriter",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R137",
  "title": "Content writer",
  "entry_pay": 3462,
  "settled_pay": 4200,
  "reskill_months": 3.0,
  "reskill_nett_base": 0.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "marketing",
  "domain_adjacent": [
   "design"
  ],
  "gate_type": "portfolio",
  "gate_detail": "Hiring gates on published writing; documented real work beats badge collecting",
  "pay_confidence": "high",
  "reskill_source": "https://editorialge.com/free-certifications-for-digital-marketers/",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R138",
  "title": "PR / corporate communications executive",
  "entry_pay": 2400,
  "settled_pay": 3440,
  "reskill_months": 0.0,
  "reskill_nett_base": 1200.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "marketing",
  "domain_adjacent": [],
  "gate_type": "portfolio",
  "gate_detail": "IPRS issues a certificate of attendance only, not a qualification; hiring gates on writing samples and media-relations experience",
  "pay_confidence": "med",
  "reskill_source": "https://iprs.glueup.com/event/iprs-training-introduction-to-public-relations-and-mass-communication-124790/",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R141",
  "title": "Event marketing executive",
  "entry_pay": 2320,
  "settled_pay": 3000,
  "reskill_months": 2.0,
  "reskill_nett_base": 158.44,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "marketing",
  "domain_adjacent": [
   "hospitality"
  ],
  "gate_type": "none",
  "gate_detail": "Experience-gated: hiring runs on event-execution track record; the WSQ Modular Certificate is the credible upskilling route, not a hiring requirement",
  "pay_confidence": "med",
  "reskill_source": "https://courses.myskillsfuture.gov.sg/search?q=event+management",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R142",
  "title": "Marketing analyst",
  "entry_pay": 2560,
  "settled_pay": 4000,
  "reskill_months": 1.0,
  "reskill_nett_base": 0.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "marketing",
  "domain_adjacent": [
   "data"
  ],
  "gate_type": "cert",
  "gate_detail": "No formal cert gate; GA4 certification is the recognized signal (free, retake after 24h); hiring weights demonstrable GA4 skill and case studies over the badge",
  "pay_confidence": "med",
  "reskill_source": "https://www.lovesdata.com/blog/google-analytics-4-certification/",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R144",
  "title": "Financial analyst",
  "entry_pay": 4368,
  "settled_pay": 6000,
  "reskill_months": 6.0,
  "reskill_nett_base": 1459.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "finance",
  "domain_adjacent": [
   "ops",
   "data"
  ],
  "gate_type": "none",
  "gate_detail": "No statutory licence for financial analysts; employers screen on CFA progress and degree",
  "pay_confidence": "high",
  "reskill_source": "https://www.swiftintellect.com/post/cfa-level-i-exam-dates-fees-registration-2025-2026-deadlines-scheduling-rescheduling",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R145",
  "title": "Credit analyst",
  "entry_pay": 4368,
  "settled_pay": 6000,
  "reskill_months": 6.0,
  "reskill_nett_base": 1459.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "finance",
  "domain_adjacent": [
   "finance",
   "ops"
  ],
  "gate_type": "none",
  "gate_detail": "No statutory licence for credit analysts; banks commonly ask for CFA progress; Level I covers financial reporting and corporate issuers",
  "pay_confidence": "high",
  "reskill_source": "https://www.swiftintellect.com/post/cfa-level-i-exam-dates-fees-registration-2025-2026-deadlines-scheduling-rescheduling",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R147",
  "title": "Treasury analyst",
  "entry_pay": 6200,
  "settled_pay": 7524,
  "reskill_months": 0.5,
  "reskill_nett_base": 1613.2,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "finance",
  "domain_adjacent": [
   "finance",
   "ops"
  ],
  "gate_type": "none",
  "gate_detail": "No statutory licence; course is a skills top-up for junior traders/sales with existing markets knowledge",
  "pay_confidence": "high",
  "reskill_source": "https://fmasg.org.sg/wp-content/uploads/2024/04/Prospectus_Financial-Markets-Trader-Sales-Foundation-virtual.pdf",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R149",
  "title": "Tax associate",
  "entry_pay": 2880,
  "settled_pay": 3440,
  "reskill_months": 3.0,
  "reskill_nett_base": 1090.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "finance",
  "domain_adjacent": [
   "finance"
  ],
  "gate_type": "none",
  "gate_detail": "No statutory licence; Tax Academy certificate is the industry entry signal; exam is optional",
  "pay_confidence": "high",
  "reskill_source": "https://www.taxacademy.sg/files/Intake_1_Course_brochure_L1_IT_2025_v2.pdf",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R150",
  "title": "Fund operations / settlements analyst",
  "entry_pay": 2800,
  "settled_pay": 4293,
  "reskill_months": 8.0,
  "reskill_nett_base": 911.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "finance",
  "domain_adjacent": [
   "ops"
  ],
  "gate_type": "cert",
  "gate_detail": "No entry requirements per CISI; IOC is the operations-industry qualification",
  "pay_confidence": "med",
  "reskill_source": "https://www.cisi.org/cisiweb2/cisi-website/why-choose-a-CISI-qualification/getting-started/price-list",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R151",
  "title": "Trade finance executive",
  "entry_pay": 2800,
  "settled_pay": 4293,
  "reskill_months": 6.0,
  "reskill_nett_base": 1248.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "finance",
  "domain_adjacent": [
   "ops"
  ],
  "gate_type": "cert",
  "gate_detail": "Professional certification managed with the ICC; no statutory licence for trade finance executives",
  "pay_confidence": "med",
  "reskill_source": "https://libf.in/study/certificate-for-documentary-credit-specialists-cdcs/",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R152",
  "title": "Bank operations officer",
  "entry_pay": 2000,
  "settled_pay": 4120,
  "reskill_months": 8.0,
  "reskill_nett_base": 911.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "finance",
  "domain_adjacent": [
   "ops"
  ],
  "gate_type": "cert",
  "gate_detail": "No entry requirements per CISI; used by major banks as a benchmarking tool per CISI",
  "pay_confidence": "med",
  "reskill_source": "https://www.cisi.org/cisiweb2/cisi-website/why-choose-a-CISI-qualification/getting-started/price-list",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R153",
  "title": "Insurance underwriter",
  "entry_pay": 3840,
  "settled_pay": 5593,
  "reskill_months": 2.0,
  "reskill_nett_base": 158.05,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "finance",
  "domain_adjacent": [
   "finance"
  ],
  "gate_type": "none",
  "gate_detail": "No statutory licence for salaried underwriters; SCI CGI is the industry foundation and feeds into the SCI Diploma/Advanced Diploma",
  "pay_confidence": "high",
  "reskill_source": "https://www.scicollege.org.sg/docs/FeeRevision2026.pdf",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R154",
  "title": "Bookkeeper",
  "entry_pay": 1434,
  "settled_pay": 2560,
  "reskill_months": 2.0,
  "reskill_nett_base": 528.05,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "finance",
  "domain_adjacent": [
   "ops"
  ],
  "gate_type": "none",
  "gate_detail": "No licence for bookkeepers; provider calls this the recommended minimum entry qualification for bookkeeping jobs",
  "pay_confidence": "high",
  "reskill_source": "https://www.inspizone.com/lcci-level-2-bookkeeping-accounting/",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R155",
  "title": "Accounts executive (AP/AR)",
  "entry_pay": 2000,
  "settled_pay": 2672,
  "reskill_months": 0.5,
  "reskill_nett_base": 472.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "finance",
  "domain_adjacent": [
   "ops"
  ],
  "gate_type": "none",
  "gate_detail": "No licence; 2-day tools top-up that strengthens Xero/QuickBooks transactional skills",
  "pay_confidence": "med",
  "reskill_source": "https://www.tertiarycourses.com.sg/media/courses/brochures/TGS-2023020565-SG.pdf?v=1780045517",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R156",
  "title": "Corporate secretarial executive",
  "entry_pay": 2400,
  "settled_pay": 3600,
  "reskill_months": 36.0,
  "reskill_nett_base": 6349.25,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "finance",
  "domain_adjacent": [
   "finance"
  ],
  "gate_type": "cert",
  "gate_detail": "Chartered Governance professional qualification; the standard credential for company-secretarial practice",
  "pay_confidence": "med",
  "reskill_source": "https://acm.edu.sg/Preparatory-Course-for-CGI-Chartered-Governance-Qualifying-Programme-(CGQP)---Part-Time",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R159",
  "title": "Credit control / collections executive",
  "entry_pay": 2000,
  "settled_pay": 2672,
  "reskill_months": 12.0,
  "reskill_nett_base": 998.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "finance",
  "domain_adjacent": [
   "ops"
  ],
  "gate_type": "cert",
  "gate_detail": "Professional certification from the Chartered Institute of Credit Management (UK); no statutory licence",
  "pay_confidence": "med",
  "reskill_source": "https://www.cicm.com/static/05ac2274-3cea-4c89-a6cefe9e5dfb1d17/CICM-Qualfication-fees-2025.pdf",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R160",
  "title": "Talent acquisition specialist",
  "entry_pay": 3800,
  "settled_pay": 4567,
  "reskill_months": 1.0,
  "reskill_nett_base": 649.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "people",
  "domain_adjacent": [
   "people"
  ],
  "gate_type": "cert",
  "gate_detail": "IHRP-CA is the national HR credential (MOM-backed); not statutory. TA hiring is experience-led.",
  "pay_confidence": "high",
  "reskill_source": "https://shri.org.sg/courses/hr-development-roadmap-to-ihrp-certified-associate-ca/",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R161",
  "title": "Compensation and benefits executive",
  "entry_pay": 3600,
  "settled_pay": 6000,
  "reskill_months": 12.0,
  "reskill_nett_base": 3787.5,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "people",
  "domain_adjacent": [
   "finance",
   "data"
  ],
  "gate_type": "cert",
  "gate_detail": "Specialist C&B diploma; not statutory. Many comp execs instead enter via HR generalist + IHRP.",
  "pay_confidence": "high",
  "reskill_source": "https://shri.org.sg/courses/diploma-in-compensation-and-benefit-management/",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R162",
  "title": "HRIS analyst",
  "entry_pay": 3440,
  "settled_pay": 5200,
  "reskill_months": 3.0,
  "reskill_nett_base": 649.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "people",
  "domain_adjacent": [
   "tech",
   "data"
  ],
  "gate_type": "none",
  "gate_detail": "No statutory cert and no dedicated SG cert route; employers hire on HR process knowledge plus HRIS system exposure.",
  "pay_confidence": "med",
  "reskill_source": "https://shri.org.sg/courses/hr-development-roadmap-to-ihrp-certified-associate-ca/",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R163",
  "title": "Employee relations specialist",
  "entry_pay": 2400,
  "settled_pay": 4234,
  "reskill_months": 1.0,
  "reskill_nett_base": 649.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "people",
  "domain_adjacent": [
   "finance"
  ],
  "gate_type": "cert",
  "gate_detail": "No statutory licence; working knowledge of SG employment law is the de-facto gate and this course is IHRP-accredited for it.",
  "pay_confidence": "med",
  "reskill_source": "https://shri.org.sg/courses/hr-development-roadmap-to-ihrp-certified-associate-ca/",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R164",
  "title": "Payroll specialist",
  "entry_pay": 2320,
  "settled_pay": 3405,
  "reskill_months": 2.0,
  "reskill_nett_base": 974.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "people",
  "domain_adjacent": [
   "finance",
   "ops"
  ],
  "gate_type": "cert",
  "gate_detail": "SoA-based payroll credential; no statutory licence. Covers CPF/SDL, payroll software, statutory reporting.",
  "pay_confidence": "med",
  "reskill_source": "https://shri.org.sg/courses/certificate-in-payroll-administration/",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R166",
  "title": "HR shared-services specialist",
  "entry_pay": 2400,
  "settled_pay": 3200,
  "reskill_months": 1.0,
  "reskill_nett_base": 590.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "people",
  "domain_adjacent": [
   "ops"
  ],
  "gate_type": "none",
  "gate_detail": "Entry-level HR ops; no cert gate. WSQ SoA covering Employment Act basics, payroll/CPF/SDL and HRMS software.",
  "pay_confidence": "med",
  "reskill_source": "https://beta.infotech.edu.sg/contents/images/course-revamp/brouchures/wsq-basichr.pdf",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R170",
  "title": "Account executive (tech sales)",
  "entry_pay": 3200,
  "settled_pay": 6746,
  "reskill_months": 0.1,
  "reskill_nett_base": 472.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "tech",
  "domain_adjacent": [
   "marketing"
  ],
  "gate_type": "none",
  "gate_detail": "No statutory licence or mandatory cert to sell tech/SaaS products in Singapore. De-facto gate: quota track record and discovery/demo ability.",
  "pay_confidence": "med",
  "reskill_source": "https://www.tertiarycourses.com.sg/media/courses/brochures/TGS-2025052342-SG.pdf?v=1780045557 - TGS-2025052342; SC 39 and below nett S$472 incl GST (50% SSG); SC 40+ S$312 incl GST; full fee S$800 + GST",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R171",
  "title": "Retail assistant",
  "entry_pay": 1840,
  "settled_pay": 1886,
  "reskill_months": 0.1,
  "reskill_nett_base": 472.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "retail",
  "domain_adjacent": [],
  "gate_type": "none",
  "gate_detail": "No statutory licence or mandatory cert for shop-floor retail in Singapore. Retail PWM sets wage floors and training requirements, not entry gates.",
  "pay_confidence": "med",
  "reskill_source": "https://www.tertiarycourses.com.sg/media/courses/brochures/TGS-2025052342-SG.pdf?v=1780045557 - TGS-2025052342; SC 39 and below nett S$472 incl GST (50% SSG); SC 40+ S$312 incl GST; full fee S$800 + GST",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 },
 {
  "id": "R172",
  "title": "Store manager",
  "entry_pay": 2400,
  "settled_pay": 3600,
  "reskill_months": 0.1,
  "reskill_nett_base": 472.0,
  "reskill_nett_40plus": null,
  "reskill_list_price": null,
  "allowance": 0,
  "incomeStability": "stable",
  "domain_primary": "retail",
  "domain_adjacent": [],
  "gate_type": "none",
  "gate_detail": "No statutory licence for retail management in Singapore. De-facto gate: team-lead track record and rostering/inventory ownership.",
  "pay_confidence": "med",
  "reskill_source": "https://www.tertiarycourses.com.sg/media/courses/brochures/TGS-2025052342-SG.pdf?v=1780045557 - TGS-2025052342; SC 39 and below nett S$472 incl GST (50% SSG); SC 40+ S$312 incl GST; full fee S$800 + GST",
  "gates": {},
  "hours_score": 0,
  "sovereignty_score": 0,
  "meaning_score": 0,
  "stability_score": 0,
  "v2": {
   "chip": null,
   "gateMonths": null
  }
 }
];
